### ISSUE TITLE
IdFieldDoesNotExistException even when Id exists

### ISSUE THREAD

**Issue by Brblol** [epsilonlabsllc/DataManagement#4]
I had declared the int variable with the @Id annotation but I kept getting the exception IdFieldDoesNotExistException when I tried to write an the object to the database.

The actual issue turned out to be, that had a none storable variable in my class. I had a Date variable. The exception is very miss leading but you must remove any none storable variables. I converted my Date to long and stored Date().getTime() instead

It took me about half a day to figure it out. It must have also shortened my life by a few years due to the amount of stress it caused me so I thought I'd share so hopefully it will help someone else.

**Comment by skmpowdjy** [comment]
This is stated in the readme: "the class should not have any instance variables that are not either primitive types, strings, or other storable objects."

**Comment by arunkumar9t2** [comment]
I get this exception as well. My case is entirely different. This library used to work without any issues pre-lollipop. 
As soon I upgraded my phone to Nexus 4, I get this exception when I try to add(). 
I double checked the code and there were no non primitive variables. I only get this error on lollipop. 
Is it possible to have a look at this issue? I have too much dependency on this library and would require much code changes if I am to look for alternatives.

Here are the fields : 
    @Id
    private int ident;
    private String presetName;
    private String panelWdgtsBG;
    private String panelBG;
    private String panelWdgtsText;
    private String mainWdgtsBG;
    private String mainWdgtsText;

**Comment by skmpowdjy** [comment]
@arunkumar9t2 Your issue is an incompatibility with the new ART runtime in Lollipop.  See the open issue here: https://github.com/epsilonlabsllc/DataManagement/issues/6
